[package]
name = "basename"
version = "0.0.1"
authors = []

[lib]
name = "basename"
path = "basename.rs"

[dependencies]
getopts = "*"
libc = "*"
uucore = { path="../uucore" }

[[bin]]
name="basename"
path="basename.rs"
