[package]
name = "uu_tty"
version = "0.0.1"
authors = []
license = "MIT"

[lib]
path = "src/tty.rs"

[dependencies]
getopts = "0.2.18"
libc = "0.2.42"
uucore = { version="0.0.3", package="uucore", git="https://github.com/uutils/uucore.git", branch="canary", features=["fs"] }
uucore_procs = { version="0.0.3", package="uucore_procs", git="https://github.com/uutils/uucore.git", branch="canary" }

[[bin]]
name = "tty"
path = "src/main.rs"
