[package]
name = "uu_groups"
version = "0.0.1"
authors = []
license = "MIT"

[lib]
path = "src/groups.rs"

[dependencies]
uucore = { version="0.0.3", package="uucore", git="https://github.com/uutils/uucore.git", branch="canary", features=["entries"] }
uucore_procs = { version="0.0.3", package="uucore_procs", git="https://github.com/uutils/uucore.git", branch="canary" }

[[bin]]
name = "groups"
path = "src/main.rs"
