[package]
name = "mkdir"
version = "0.0.1"
authors = []

[lib]
name = "mkdir"
path = "mkdir.rs"

[dependencies]
getopts = "*"
libc = "*"
uucore = { path="../uucore" }

[[bin]]
name="mkdir"
path="mkdir.rs"
