[package]
name = "truncate"
version = "0.0.1"
authors = []
build = "../../mkmain.rs"

[lib]
name = "uu_truncate"
path = "truncate.rs"

[dependencies]
getopts = "0.2.18"
uucore = { path="../uucore" }

[[bin]]
name = "truncate"
path = "../../uumain.rs"
