[package]
name = "uu_od"
version = "0.0.1"
authors = []
license = "MIT"

[lib]
path = "src/od.rs"

[dependencies]
byteorder = "1.3.2"
getopts = "0.2.18"
half = "1.1.1"
libc = "0.2.42"
uucore = { version="0.0.3", package="uucore", git="https://github.com/uutils/uucore.git", branch="canary" }
uucore_procs = { version="0.0.3", package="uucore_procs", git="https://github.com/uutils/uucore.git", branch="canary" }

[[bin]]
name = "od"
path = "src/main.rs"
