[package]
name = "cksum"
version = "0.0.1"
authors = []

[lib]
name = "cksum"
path = "cksum.rs"

[dependencies]
getopts = "*"
libc = "*"
uucore = { path="../uucore" }

[[bin]]
name="cksum"
path="cksum.rs"
