[package]
name = "uu_date"
version = "0.0.1"
authors = []
license = "MIT"

[lib]
path = "src/date.rs"

[dependencies]
chrono = "0.4.4"
clap = "2.32"
uucore = { version="0.0.3", package="uucore", git="https://github.com/uutils/uucore.git", branch="canary" }
uucore_procs = { version="0.0.3", package="uucore_procs", git="https://github.com/uutils/uucore.git", branch="canary" }

[[bin]]
name = "date"
path = "src/main.rs"
