[package]
name = "base64"
version = "0.0.1"
authors = []

[lib]
name = "base64"
path = "base64.rs"

[dependencies]
getopts = "*"
libc = "*"
rustc-serialize = "*"
uucore = { path="../uucore" }

[[bin]]
name="base64"
path="base64.rs"
