[package]
name = "uu_stat"
version = "0.0.1"
authors = ["uutils developers"]
license = "MIT"
description = "stat ~ (uutils) display FILE status"

homepage = "https://github.com/uutils/coreutils"
repository = "https://github.com/uutils/coreutils/tree/master/src/uu/stat"
keywords = ["coreutils", "uutils", "cross-platform", "core", "cli", "util", "utility"]
categories = ["command-line-utilities"]
edition = "2018"

[lib]
path = "src/stat.rs"

[dependencies]
getopts = "0.2.18"
time = "0.1.40"
uucore = { version="0.0.3", package="uucore", git="https://github.com/uutils/uucore.git", branch="canary", features=["entries"] }
uucore_procs = { version="0.0.3", package="uucore_procs", git="https://github.com/uutils/uucore.git", branch="canary" }

[[bin]]
name = "stat"
path = "src/main.rs"
