[package]
name = "readlink"
version = "0.0.1"
authors = []

[lib]
name = "readlink"
path = "readlink.rs"

[dependencies]
getopts = "*"
libc = "*"
uucore = { path="../uucore" }

[[bin]]
name="readlink"
path="readlink.rs"
