language: rust
matrix:
  include:
    - rust: stable
      env: FEATURES=''
    - rust: beta
      env: FEATURES=''
    - rust: nightly
      env: FEATURES=nightly
os:
 - linux
 - osx
cache:
 directories:
  - $HOME/.cargo
sudo: false
script:
  - cargo build --features "$FEATURES"
  - cargo test --features "$FEATURES" --no-fail-fast
