language: rust
matrix:
  fast_finish: true
  include:
    - rust: stable
      os: linux
      env: FEATURES=''
    - rust: stable
      os: osx
      env: FEATURES=''
    - rust: beta
      os: linux
      env: FEATURES=''
    - rust: beta
      os: osx
      env: FEATURES=''
    - rust: nightly
      os: linux
      env: FEATURES=nightly
    - rust: nightly
      os: osx
      env: FEATURES=nightly
    - rust: nightly
      os: linux
      env: FEATURES=nightly,redox CC=x86_64-unknown-redox-gcc CARGO_ARGS='--no-default-features --target=x86_64-unknown-redox' REDOX=1
  allow_failures:
    - rust: nightly
      os: linux
      env: FEATURES=nightly,redox CC=x86_64-unknown-redox-gcc CARGO_ARGS='--no-default-features --target=x86_64-unknown-redox' REDOX=1

cache:
  directories:
    - $HOME/.cargo

sudo: true

before_install:
  - if [ $REDOX ]; then ./.travis/redox-toolchain.sh; fi

script:
  - cargo build $CARGO_ARGS --features "$FEATURES"
  - if [ ! $REDOX ]; then cargo test $CARGO_ARGS --features "$FEATURES" --no-fail-fast; fi
  - mkdir installdir_test
  - DESTDIR=installdir_test make install
  - "[ `ls installdir_test/usr/bin | wc -l` -gt 0 ]"

addons:
  apt:
    packages:
      - libssl-dev

after_success: |
  if [ "$TRAVIS_OS_NAME" = linux -a "$TRAVIS_RUST_VERSION" = stable ]; then
    bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi

