language: rust
rust:
  - stable
  - beta
  - nightly
os:
 - linux
 - osx
cache:
 directories:
  - $HOME/.cargo
sudo: false
script:
  - cargo build
  - cargo test --no-fail-fast
matrix:
  allow_failures:
    - rust: stable
    - rust: beta
    - os: osx
