[package]
name = "uu_df"
version = "0.0.1"
authors = []
license = "MIT"

[lib]
path = "src/df.rs"

[dependencies]
clap = "2.32"
libc = "0.2"
number_prefix = "0.2"
uucore = { version="0.0.3", package="uucore", git="https://github.com/uutils/uucore.git", branch="canary" }
uucore_procs = { version="0.0.3", package="uucore_procs", git="https://github.com/uutils/uucore.git", branch="canary" }

[target.'cfg(target_os = "windows")'.dependencies]
kernel32-sys = "0.2"
winapi = { version = "0.3", features = ["handleapi", "winerror"] }

[[bin]]
name = "df"
path = "src/main.rs"
