[package]
name = "unexpand"
version = "0.0.1"
authors = []

[lib]
name = "unexpand"
path = "unexpand.rs"

[dependencies]
getopts = "*"
libc = "*"
unicode-width = "*"
uucore = { path="../uucore" }

[[bin]]
name="unexpand"
path="unexpand.rs"
