[package]
name = "relpath"
version = "0.0.1"
authors = []
build = "../../mkmain.rs"

[lib]
name = "uu_relpath"
path = "relpath.rs"

[dependencies]
getopts = "0.2.14"

[dependencies.uucore]
path = "../uucore"
features = ["fs"]

[[bin]]
name = "relpath"
path = "../../uumain.rs"
