[package]
name = "relpath"
version = "0.0.1"
authors = []

[lib]
name = "relpath"
path = "relpath.rs"

[dependencies]
getopts = "*"
libc = "*"
uucore = { path="../uucore" }

[[bin]]
name="relpath"
path="relpath.rs"
