[package]
name = "rm"
version = "0.0.1"
authors = []
build = "../../mkmain.rs"

[lib]
name = "uu_rm"
path = "rm.rs"

[dependencies]
getopts = "0.2.14"
walkdir = "2.1.4"
remove_dir_all = "0.5.1"
uucore = { path="../uucore" }

[[bin]]
name = "rm"
path = "../../uumain.rs"
