[package]
name = "fold"
version = "0.0.1"
authors = []
build = "../../mkmain.rs"

[lib]
name = "uu_fold"
path = "fold.rs"

[dependencies]
uucore = { path="../uucore" }

[[bin]]
name = "fold"
path = "../../uumain.rs"
