[package]
name = "fold"
version = "0.0.1"
authors = []

[lib]
name = "fold"
path = "fold.rs"

[dependencies]
getopts = "*"
libc = "*"
uucore = { path="../uucore" }

[[bin]]
name="fold"
path="fold.rs"
