[package]
name = "uu_nproc"
version = "0.0.1"
authors = []
license = "MIT"

[lib]
path = "src/nproc.rs"

[dependencies]
getopts = "0.2.18"
libc = "0.2.42"
num_cpus = "1.10"
uucore = { version="0.0.3", package="uucore", git="https://github.com/uutils/uucore.git", branch="canary", features=["fs"] }
uucore_procs = { version="0.0.3", package="uucore_procs", git="https://github.com/uutils/uucore.git", branch="canary" }

[[bin]]
name = "nproc"
path = "src/main.rs"
