[project]
name = "deps"
version = "0.0.0"

[lib]
name = "null"

[dependencies]
libc = "0.1.8"
getopts = "0.2.11"
bit-vec = "0.4.0"
bit-set = "0.2.0"
num_cpus = "*"
rand = "0.3.8"
regex = "0.1.38"
rust-crypto = "0.2.31"
rustc-serialize = "0.3.15"
time = "0.1.26"
unicode-width = "0.1.1"
