[package]
name = "paste"
version = "0.0.1"
authors = []

[lib]
name = "paste"
path = "paste.rs"

[dependencies]
getopts = "*"
libc = "*"
uucore = { path="../uucore" }

[[bin]]
name="paste"
path="paste.rs"
