[package]
name = "uu_hashsum"
version = "0.0.1"
authors = []
license = "MIT"

[lib]
path = "src/hashsum.rs"

[dependencies]
digest = "0.6.2"
getopts = "0.2.18"
hex = "0.2.0"
libc = "0.2.42"
md5 = "0.3.5"
regex = "1.0.1"
regex-syntax = "0.6.7"
sha1 = "0.6.0"
sha2 = "0.6.0"
sha3 = "0.6.0"
uucore = { version="0.0.3", package="uucore", git="https://github.com/uutils/uucore.git", branch="canary" }
uucore_procs = { version="0.0.3", package="uucore_procs", git="https://github.com/uutils/uucore.git", branch="canary" }

[[bin]]
name = "hashsum"
path = "src/main.rs"
