[package]
name = "uu_base64"
version = "0.0.1"
authors = []
license = "MIT"

[lib]
path = "src/base64.rs"

[dependencies]
uucore = { version="0.0.3", package="uucore", git="https://github.com/uutils/uucore.git", branch="canary", features = ["encoding"] }
uucore_procs = { version="0.0.3", package="uucore_procs", git="https://github.com/uutils/uucore.git", branch="canary" }

[[bin]]
name = "base64"
path = "src/main.rs"
