[package]
name = "uu_stdbuf_libstdbuf"
version = "0.0.1"
authors = []
license = "MIT"

[lib]
name = "libstdbuf"
path = "src/libstdbuf.rs"
crate-type = ["cdylib", "rlib"] # XXX: note: the rlib is just to prevent Cargo from spitting out a warning

[dependencies]
cpp = "0.4"
libc = "0.2"
uucore = { version="0.0.3", package="uucore", git="https://github.com/uutils/uucore.git", branch="canary" }
uucore_procs = { version="0.0.3", package="uucore_procs", git="https://github.com/uutils/uucore.git", branch="canary" }

[build-dependencies]
cpp_build = "0.4"
