[package]
name = "uu_sort"
version = "0.0.6"
authors = ["uutils developers"]
license = "MIT"
description = "sort ~ (uutils) sort input lines"

homepage = "https://github.com/uutils/coreutils"
repository = "https://github.com/uutils/coreutils/tree/master/src/uu/sort"
keywords = ["coreutils", "uutils", "cross-platform", "cli", "utility"]
categories = ["command-line-utilities"]
edition = "2018"

[lib]
path = "src/sort.rs"

[dependencies]
byteorder = "1.4.3"
extsort = "0.4.2"
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
serde = { version = "1.0", features = ["derive"] }
rayon = "1.5"
rand = "0.7"
clap = "2.33"
fnv = "1.0.7"
itertools = "0.10.0"
semver = "0.9.0"
smallvec = { version = "1.6.1", features = ["serde"] }
uucore = { version=">=0.0.8", package="uucore", path="../../uucore", features=["fs"] }
uucore_procs = { version=">=0.0.5", package="uucore_procs", path="../../uucore_procs" }

[[bin]]
name = "sort"
path = "src/main.rs"
