[package]
name = "uu_sort"
version = "0.0.1"
authors = []
license = "MIT"

[lib]
path = "src/sort.rs"

[dependencies]
getopts = "0.2.18"
itertools = "0.8.0"
semver = "0.9.0"
uucore = { version="0.0.3", package="uucore", git="https://github.com/uutils/uucore.git", branch="canary", features=["fs"] }
uucore_procs = { version="0.0.3", package="uucore_procs", git="https://github.com/uutils/uucore.git", branch="canary" }

[[bin]]
name = "sort"
path = "src/main.rs"
