[package]
name = "printenv"
version = "0.0.1"
authors = []

[lib]
name = "printenv"
path = "printenv.rs"

[dependencies]
getopts = "*"
libc = "*"
uucore = { path="../uucore" }

[[bin]]
name="printenv"
path="printenv.rs"
