[package]
name = "realpath"
version = "0.0.1"
authors = []
build = "../../mkmain.rs"

[lib]
name = "uu_realpath"
path = "realpath.rs"

[dependencies]
getopts = "0.2.14"
uucore = { path="../uucore" }

[[bin]]
name = "realpath"
path = "../../uumain.rs"
