[package]
name = "realpath"
version = "0.0.1"
authors = []

[lib]
name = "uu_realpath"
path = "realpath.rs"

[dependencies]
getopts = "*"
uucore = { path="../uucore" }

[[bin]]
name = "realpath"
path = "main.rs"
