[package]
name = "true"
version = "0.0.1"
authors = []
build = "../../mkmain.rs"

[lib]
name = "uu_true"
path = "true.rs"

[dependencies]
uucore = { path = "../uucore" }

[[bin]]
name = "true"
path = "../../uumain.rs"
