[package]
name = "uu_shred"
version = "0.0.1"
authors = []
license = "MIT"

[lib]
path = "src/shred.rs"

[dependencies]
filetime = "0.2.1"
getopts = "0.2.18"
libc = "0.2.42"
rand = "0.5"
time = "0.1.40"
uucore = { version="0.0.3", package="uucore", git="https://github.com/uutils/uucore.git", branch="canary" }
uucore_procs = { version="0.0.3", package="uucore_procs", git="https://github.com/uutils/uucore.git", branch="canary" }

[[bin]]
name = "shred"
path = "src/main.rs"
