[package]
name = "yes"
version = "0.0.1"
authors = []
description = "Repeatedly output a line with all specified STRING(s), or 'y'."
build = "../../mkmain.rs"

[lib]
name = "uu_yes"
path = "yes.rs"

[dependencies]
clap = "2.31"
uucore = { path = "../uucore" }

[[bin]]
name = "yes"
path = "../../uumain.rs"
