[package]
name = "uu_hostid"
version = "0.0.1"
authors = ["uutils developers"]
license = "MIT"
description = "hostid ~ (uutils) display the numeric identifier of the current host"

homepage = "https://github.com/uutils/coreutils"
repository = "https://github.com/uutils/coreutils/tree/master/src/uu/hostid"
keywords = ["coreutils", "uutils", "cross-platform", "core", "cli", "util", "utility"]
categories = ["command-line-utilities"]
edition = "2018"

[lib]
path = "src/hostid.rs"

[dependencies]
libc = "0.2.42"
uucore = { version="0.0.4", package="uucore", git="https://github.com/uutils/uucore.git", branch="canary" }
uucore_procs = { version="0.0.4", package="uucore_procs", git="https://github.com/uutils/uucore.git", branch="canary" }

[[bin]]
name = "hostid"
path = "src/main.rs"
