[package]
name = "tsort"
version = "0.0.1"
authors = []

[lib]
name = "uu_tsort"
path = "tsort.rs"

[dependencies]
getopts = "*"
uucore = { path="../uucore" }

[[bin]]
name = "tsort"
path = "main.rs"
