[package]
name = "tsort"
version = "0.0.1"
authors = []

[lib]
name = "tsort"
path = "tsort.rs"

[dependencies]
getopts = "*"
libc = "*"
uucore = { path="../uucore" }

[[bin]]
name="tsort"
path="tsort.rs"
