[package]
name = "sleep"
version = "0.0.1"
authors = []
build = "../../mkmain.rs"

[lib]
name = "uu_sleep"
path = "sleep.rs"

[dependencies]
getopts = "0.2.14"

[dependencies.uucore]
path = "../uucore"
features = ["parse_time"]

[[bin]]
name = "sleep"
path = "../../uumain.rs"
