[package]
name = "sleep"
version = "0.0.1"
authors = []

[lib]
name = "sleep"
path = "sleep.rs"

[dependencies]
getopts = "*"
libc = "*"
uucore = { path="../uucore" }

[[bin]]
name="sleep"
path="sleep.rs"
