[package]
name = "uu_cp"
version = "0.0.1"
authors = [
    "Jordy Dickinson <jordy.dickinson@gmail.com>",
    "Joshua S. Miller <jsmiller@uchicago.edu>",
]
license = "MIT"

[lib]
path = "src/cp.rs"

[dependencies]
clap = "2.32"
filetime = "0.2"
libc = "0.2.42"
quick-error = "1.2.3"
uucore = { version="0.0.3", package="uucore", git="https://github.com/uutils/uucore.git", branch="canary", features=["fs"] }
uucore_procs = { version="0.0.3", package="uucore_procs", git="https://github.com/uutils/uucore.git", branch="canary" }
walkdir = "2.2.8"

[target.'cfg(target_os = "linux")'.dependencies]
ioctl-sys = "0.5.2"

[target.'cfg(target_os = "windows")'.dependencies]
kernel32-sys = "0.2.2"
winapi = "0.3"

[target.'cfg(unix)'.dependencies]
xattr="0.2.1"

[[bin]]
name = "cp"
path = "src/main.rs"
