[package]
name = "uu_mv"
version = "0.0.1"
authors = []
license = "MIT"

[lib]
path = "src/mv.rs"

[dependencies]
getopts = "0.2.18"
fs_extra = "1.1.0"
uucore = { version="0.0.3", package="uucore", git="https://github.com/uutils/uucore.git", branch="canary" }
uucore_procs = { version="0.0.3", package="uucore_procs", git="https://github.com/uutils/uucore.git", branch="canary" }

[[bin]]
name = "mv"
path = "src/main.rs"
