[package]
name = "kill"
version = "0.0.1"
authors = []

[lib]
name = "kill"
path = "kill.rs"

[dependencies]
getopts = "*"
libc = "*"
uucore = { path="../uucore" }

[[bin]]
name="kill"
path="kill.rs"
