[package]
name = "uu_id"
version = "0.0.1"
authors = []
license = "MIT"

[lib]
path = "src/id.rs"

[dependencies]
uucore = { version="0.0.3", package="uucore", git="https://github.com/uutils/uucore.git", branch="canary", features=["entries", "process"] }
uucore_procs = { version="0.0.3", package="uucore_procs", git="https://github.com/uutils/uucore.git", branch="canary" }

[[bin]]
name = "id"
path = "src/main.rs"
