[package]
name = "uu_chgrp"
version = "0.0.1"
authors = []
license = "MIT"

[lib]
path = "src/chgrp.rs"

[dependencies]
uucore = { version="0.0.3", package="uucore", git="https://github.com/uutils/uucore.git", branch="canary", features=["entries", "fs"] }
uucore_procs = { version="0.0.3", package="uucore_procs", git="https://github.com/uutils/uucore.git", branch="canary" }
walkdir = "2.2.8"

[[bin]]
name = "chgrp"
path = "src/main.rs"
