[package]
name = "uu_fold"
version = "0.0.1"
authors = []
license = "MIT"

[lib]
path = "src/fold.rs"

[dependencies]
uucore = { version="0.0.3", package="uucore", git="https://github.com/uutils/uucore.git", branch="canary" }
uucore_procs = { version="0.0.3", package="uucore_procs", git="https://github.com/uutils/uucore.git", branch="canary" }

[[bin]]
name = "fold"
path = "src/main.rs"
