[package]
name = "uu_tail"
version = "0.0.1"
authors = []
license = "MIT"

[lib]
path = "src/tail.rs"

[dependencies]
getopts = "0.2.18"
kernel32-sys = "0.2.2"
libc = "0.2.42"
uucore = { version="0.0.3", package="uucore", git="https://github.com/uutils/uucore.git", branch="canary" }
uucore_procs = { version="0.0.3", package="uucore_procs", git="https://github.com/uutils/uucore.git", branch="canary" }
winapi = "0.3"

[target.'cfg(target_os = "redox")'.dependencies]
redox_syscall = "0.1"

[[bin]]
name = "tail"
path = "src/main.rs"
