[package]
name = "uu_env"
version = "0.0.1"
authors = ["uutils developers"]
description = "Set each NAME to VALUE in the environment and run COMMAND"
license = "MIT"
edition = "2018"

[lib]
path = "src/env.rs"

[dependencies]
clap = "2.33"
libc = "0.2.42"
rust-ini = "0.13.0"
uucore = { version="0.0.3", package="uucore", git="https://github.com/uutils/uucore.git", branch="canary" }
uucore_procs = { version="0.0.3", package="uucore_procs", git="https://github.com/uutils/uucore.git", branch="canary" }

[[bin]]
name = "env"
path = "src/main.rs"
