[package]
name = "uu_tr"
version = "0.0.1"
authors = []
license = "MIT"

[lib]
path = "src/tr.rs"

[dependencies]
bit-set = "0.5.0"
fnv = "1.0.5"
getopts = "0.2.18"
uucore = { version="0.0.3", package="uucore", git="https://github.com/uutils/uucore.git", branch="canary" }
uucore_procs = { version="0.0.3", package="uucore_procs", git="https://github.com/uutils/uucore.git", branch="canary" }

[[bin]]
name = "tr"
path = "src/main.rs"
