[package]
name = "users"
version = "0.0.1"
authors = []

[lib]
name = "users"
path = "users.rs"

[dependencies]
getopts = "*"
libc = "*"
uucore = { path="../uucore" }

[[bin]]
name="users"
path="users.rs"
