[package]
name = "more"
version = "0.0.1"
authors = []

[lib]
name = "uu_more"
path = "more.rs"

[dependencies]
getopts = "*"
uucore = { path="../uucore" }

[target.'cfg(all(unix, not(target_os = "fuchsia")))'.dependencies]
nix = "*"

[[bin]]
name = "more"
path = "main.rs"
