[package]
name = "more"
version = "0.0.1"
authors = []

[lib]
name = "uu_more"
path = "more.rs"

[dependencies]
getopts = "*"
libc = "*"
uucore = { path="../uucore" }

[target."cfg(unix)".dependencies]
nix = "*"

[[bin]]
name = "more"
path = "main.rs"
