[package]
name = "od"
version = "0.0.1"
authors = []

[lib]
name = "uu_od"
path = "od.rs"

[dependencies]
getopts = "*"
libc = "*"
unindent = "*"
byteorder = "*"

[[bin]]
name = "od"
path = "main.rs"
