[package]
name = "uu_chroot"
version = "0.0.1"
authors = ["uutils developers"]
license = "MIT"
description = "chroot ~ (uutils) run a command under a new root directory"

homepage = "https://github.com/uutils/coreutils"
repository = "https://github.com/uutils/coreutils/tree/master/src/uu/chroot"

[lib]
path = "src/chroot.rs"

[dependencies]
getopts = "0.2.18"
uucore = { version="0.0.3", package="uucore", git="https://github.com/uutils/uucore.git", branch="canary", features=["entries"] }
uucore_procs = { version="0.0.3", package="uucore_procs", git="https://github.com/uutils/uucore.git", branch="canary" }

[[bin]]
name = "chroot"
path = "src/main.rs"
