[package]
name = "uu_sync"
version = "0.0.1"
authors = []
license = "MIT"

[lib]
path = "src/sync.rs"

[dependencies]
getopts = "0.2.18"
kernel32-sys = "0.2.2"
libc = "0.2.42"
uucore = { version="0.0.3", package="uucore", git="https://github.com/uutils/uucore.git", branch="canary", features=["wide"] }
uucore_procs = { version="0.0.3", package="uucore_procs", git="https://github.com/uutils/uucore.git", branch="canary" }
winapi = { version = "0.3", features = ["handleapi", "winerror"] }

[[bin]]
name = "sync"
path = "src/main.rs"
