[package]
name = "link"
version = "0.0.1"
authors = []

[lib]
name = "link"
path = "link.rs"

[dependencies]
getopts = "*"
libc = "*"
uucore = { path="../uucore" }

[[bin]]
name="link"
path="link.rs"
