[package]
name = "hostname"
version = "0.0.1"
authors = []

[lib]
name = "hostname"
path = "hostname.rs"

[dependencies]
getopts = "*"
libc = "*"
uucore = { path="../uucore" }

[[bin]]
name="hostname"
path="hostname.rs"
