[package]
name = "uu_timeout"
version = "0.0.1"
authors = []
license = "MIT"

[lib]
path = "src/timeout.rs"

[dependencies]
getopts = "0.2.18"
libc = "0.2.42"
time = "0.1.40"
uucore = { version="0.0.3", package="uucore", git="https://github.com/uutils/uucore.git", branch="canary", features=["parse_time", "process", "signals"] }
uucore_procs = { version="0.0.3", package="uucore_procs", git="https://github.com/uutils/uucore.git", branch="canary" }

[[bin]]
name = "timeout"
path = "src/main.rs"
