[package]
name = "uu_whoami"
version = "0.0.1"
authors = []
license = "MIT"
description = "Diplay effective user ID"

[lib]
path = "src/whoami.rs"

[dependencies]
advapi32-sys = "0.2.0"
clap = "2.32"
uucore = { version="0.0.3", package="uucore", git="https://github.com/uutils/uucore.git", branch="canary", features=["entries", "wide"] }
uucore_procs = { version="0.0.3", package="uucore_procs", git="https://github.com/uutils/uucore.git", branch="canary" }
winapi = { version = "0.3", features = ["lmcons"] }

[[bin]]
name = "whoami"
path = "src/main.rs"
