[package]
name = "uu_dd"
version = "0.0.6"
authors = ["uutils developers"]
license = "MIT"
description = "dd ~ (uutils) copy and convert files"

homepage = "https://github.com/uutils/coreutils"
repository = "https://github.com/uutils/coreutils/tree/master/src/uu/dd"
keywords = ["coreutils", "uutils", "cross-platform", "cli", "utility"]
categories = ["command-line-utilities"]
edition = "2018"

[lib]
path = "src/dd.rs"

[dependencies]
byte-unit = "4.0"
clap = { version = "2.33", features = [ "wrap_help" ] }
debug_print = "1.0"
gcd = "2.0"
libc = "0.2"
signal-hook = "0.3.9"
uucore = { version=">=0.0.8", package="uucore", path="../../uucore" }
uucore_procs = { version=">=0.0.5", package="uucore_procs", path="../../uucore_procs" }

[dev-dependencies]
tempfile = "^3"

[[bin]]
name = "dd"
path = "src/main.rs"
