[package]
name = "uu_dd"
version = "0.0.4"
authors = ["uutils developers"]
license = "MIT"
description = "dd ~ (uutils) copy and convert files"

homepage = "https://github.com/uutils/coreutils"
repository = "https://github.com/uutils/coreutils/tree/master/src/uu/dd"
keywords = ["coreutils", "uutils", "cross-platform", "cli", "utility"]
categories = ["command-line-utilities"]
edition = "2018"

[lib]
path = "src/dd.rs"

[dependencies]
byte-unit = "4.0"
debug_print = "1.0"
# Probably best to keep this identical to the version of getopts in the uucore crate
getopts = "<= 0.2.21"
gcd = "2.0"
libc = "0.2"
signal-hook = "0.3.9"
uucore = { version=">=0.0.7", package="uucore", path="../../uucore" }
uucore_procs = { version=">=0.0.5", package="uucore_procs", path="../../uucore_procs" }

[dev-dependencies]
md-5 = "0.9"
hex-literal = "0.3"

[[bin]]
name = "dd"
path = "src/main.rs"
