[package]
name = "uu_more"
version = "0.0.1"
authors = []
license = "MIT"

[lib]
path = "src/more.rs"

[dependencies]
getopts = "0.2.18"
uucore = { version="0.0.3", package="uucore", git="https://github.com/uutils/uucore.git", branch="canary" }
uucore_procs = { version="0.0.3", package="uucore_procs", git="https://github.com/uutils/uucore.git", branch="canary" }

[target.'cfg(target_os = "redox")'.dependencies]
redox_termios = "0.1"
redox_syscall = "0.1"

[target.'cfg(all(unix, not(target_os = "fuchsia")))'.dependencies]
nix = "0.8.1"

[[bin]]
name = "more"
path = "src/main.rs"
