[package]
name = "cp"
version = "0.0.1"
authors = []

[lib]
name = "uu_cp"
path = "cp.rs"

[dependencies]
getopts = "0.2.14"
libc = "0.2.26"
uucore = { path="../uucore" }
walkdir = "1.0.7"

[[bin]]
name = "cp"
path = "main.rs"
