[package]
name = "head"
version = "0.0.1"
authors = []
build = "../../mkmain.rs"

[lib]
name = "uu_head"
path = "head.rs"

[dependencies]
libc = "0.2.42"
uucore = { path="../uucore" }

[[bin]]
name = "head"
path = "../../uumain.rs"
