[package]
name = "head"
version = "0.0.1"
authors = []

[lib]
name = "head"
path = "head.rs"

[dependencies]
getopts = "*"
libc = "*"
uucore = { path="../uucore" }

[[bin]]
name="head"
path="head.rs"
