[package]
name = "cut"
version = "0.0.1"
authors = []

[lib]
name = "uu_cut"
path = "cut.rs"

[dependencies]
getopts = "*"
libc = "*"
uucore = { path="../uucore" }

[[bin]]
name = "cut"
path = "main.rs"
