[package]
name = "cut"
version = "0.0.1"
authors = []
build = "../../mkmain.rs"

[lib]
name = "uu_cut"
path = "cut.rs"

[dependencies]
uucore = { path="../uucore" }

[[bin]]
name = "cut"
path = "../../uumain.rs"
