[package]
name = "uu_who"
version = "0.0.1"
authors = ["uutils developers"]
license = "MIT"
description = "who ~ (uutils) display information about currently logged-in users"

homepage = "https://github.com/uutils/coreutils"
repository = "https://github.com/uutils/coreutils/tree/master/src/uu/who"
keywords = ["coreutils", "uutils", "cross-platform", "core", "cli", "util", "utility"]
categories = ["command-line-utilities"]
edition = "2018"

[lib]
path = "src/who.rs"

[dependencies]
uucore = { version="0.0.3", package="uucore", git="https://github.com/uutils/uucore.git", branch="canary", features=["utmpx"] }
uucore_procs = { version="0.0.3", package="uucore_procs", git="https://github.com/uutils/uucore.git", branch="canary" }
## optional
clippy = { version = "0.0.212", optional = true }

[[bin]]
name = "who"
path = "src/main.rs"
