[package]
name = "uu_mknod"
version = "0.0.1"
authors = ["uutils developers"]
license = "MIT"
description = "mknod ~ (uutils) create special file NAME of TYPE"

homepage = "https://github.com/uutils/coreutils"
repository = "https://github.com/uutils/coreutils/tree/master/src/uu/mknod"
keywords = ["coreutils", "uutils", "cross-platform", "core", "cli", "util", "utility"]
categories = ["command-line-utilities"]
edition = "2018"

[lib]
name = "uu_mknod"
path = "src/mknod.rs"

[dependencies]
getopts = "0.2.18"
libc = "^0.2.42"
uucore = { version="0.0.4", package="uucore", git="https://github.com/uutils/uucore.git", branch="canary" }
uucore_procs = { version="0.0.4", package="uucore_procs", git="https://github.com/uutils/uucore.git", branch="canary" }

[[bin]]
name = "mknod"
path = "src/main.rs"
