[package]
name = "uu_expand"
version = "0.0.1"
authors = []
license = "MIT"
description = "expand ~ (uutils) convert input tabs to spaces"

homepage = "https://github.com/uutils/coreutils"
repository = "https://github.com/uutils/coreutils/tree/master/src/uu/expand"
keywords = ["coreutils", "uutils", "cross-platform", "core", "cli", "util", "utility"]
categories = ["command-line-utilities"]
edition = "2018"

[lib]
path = "src/expand.rs"

[dependencies]
getopts = "0.2.18"
unicode-width = "0.1.5"
uucore = { version="0.0.3", package="uucore", git="https://github.com/uutils/uucore.git", branch="canary" }
uucore_procs = { version="0.0.3", package="uucore_procs", git="https://github.com/uutils/uucore.git", branch="canary" }

[[bin]]
name = "expand"
path = "src/main.rs"
