[package]
name = "stdbuf"
version = "0.0.1"
authors = []

[lib]
name = "stdbuf"
path = "stdbuf.rs"

[dependencies]
getopts = "*"
libc = "*"
uucore = { path="../uucore" }

[[bin]]
name="stdbuf"
path="stdbuf.rs"
