[package]
name = "dircolors"
version = "0.0.1"
authors = []
build = "../../mkmain.rs"

[lib]
name = "uu_dircolors"
path = "dircolors.rs"

[dependencies]
glob = "0.2.11"
uucore = { path="../uucore" }

[[bin]]
name = "dircolors"
path = "../../uumain.rs"
