[package]
name = "uu_yes"
version = "0.0.1"
authors = []
license = "MIT"
description = "Repeatedly output a line with all specified STRING(s), or 'y'"

[lib]
path = "src/yes.rs"

[dependencies]
clap = "2.32"
uucore = { version="0.0.3", package="uucore", git="https://github.com/uutils/uucore.git", branch="canary", features=["zero-copy"] }
uucore_procs = { version="0.0.3", package="uucore_procs", git="https://github.com/uutils/uucore.git", branch="canary" }

[features]
default = []
#
latency = []

[[bin]]
name = "yes"
path = "src/main.rs"
