[package]
name = "uu_ln"
version = "0.0.1"
authors = []
license = "MIT"

[lib]
path = "src/ln.rs"

[dependencies]
libc = "0.2.42"
uucore = { version="0.0.3", package="uucore", git="https://github.com/uutils/uucore.git", branch="canary" }
uucore_procs = { version="0.0.3", package="uucore_procs", git="https://github.com/uutils/uucore.git", branch="canary" }

[[bin]]
name = "ln"
path = "src/main.rs"
