[package]
name = "date"
version = "0.0.1"
authors = []
build = "../../mkmain.rs"

[lib]
name = "uu_date"
path = "date.rs"

[dependencies]
chrono = "0.4.3"
clap = "2.31.2"
uucore = { path="../uucore" }

[[bin]]
name = "date"
path = "../../uumain.rs"
