[package]
name = "uu_cut"
version = "0.0.1"
authors = ["uutils developers"]
license = "MIT"
description = "cut ~ (uutils) display byte or field columns of input lines"

homepage = "https://github.com/uutils/coreutils"
repository = "https://github.com/uutils/coreutils/tree/master/src/uu/cut"

[lib]
path = "src/cut.rs"

[dependencies]
uucore = { version="0.0.3", package="uucore", git="https://github.com/uutils/uucore.git", branch="canary" }
uucore_procs = { version="0.0.3", package="uucore_procs", git="https://github.com/uutils/uucore.git", branch="canary" }

[[bin]]
name = "cut"
path = "src/main.rs"
