[package]
name = "uu_install"
version = "0.0.1"
authors = [
    "Ben Eills <ben@beneills.com>",
    "uutils developers",
]
license = "MIT"

[lib]
path = "src/install.rs"

[dependencies]
getopts = "0.2.18"
libc = ">= 0.2"
uucore = { version="0.0.3", package="uucore", git="https://github.com/uutils/uucore.git", branch="canary" }
uucore_procs = { version="0.0.3", package="uucore_procs", git="https://github.com/uutils/uucore.git", branch="canary" }

[dev-dependencies]
time = "0.1.40"

[[bin]]
name = "install"
path = "src/main.rs"
