[package]
name = "uu_stdbuf"
version = "0.0.1"
authors = []
license = "MIT"

[lib]
path = "src/stdbuf.rs"

[dependencies]
getopts = "0.2.18"
tempdir = "0.3.7"
uucore = { version="0.0.3", package="uucore", git="https://github.com/uutils/uucore.git", branch="canary" }
uucore_procs = { version="0.0.3", package="uucore_procs", git="https://github.com/uutils/uucore.git", branch="canary" }

[build-dependencies]
libstdbuf = { version="0.0.1", package="uu_stdbuf_libstdbuf", path="src/libstdbuf" }

[[bin]]
name = "stdbuf"
path = "src/main.rs"
