[package]
name = "uu_mkfifo"
version = "0.0.1"
authors = ["uutils developers"]
license = "MIT"
description = "mkfifo ~ (uutils) create FIFOs (named pipes)"

homepage = "https://github.com/uutils/coreutils"
repository = "https://github.com/uutils/coreutils/tree/master/src/uu/mkfifo"
keywords = ["coreutils", "uutils", "cross-platform", "core", "cli", "util", "utility"]
categories = ["command-line-utilities"]
edition = "2018"

[lib]
path = "src/mkfifo.rs"

[dependencies]
getopts = "0.2.18"
libc = "0.2.42"
uucore = { version="0.0.4", package="uucore", git="https://github.com/uutils/uucore.git", branch="canary" }
uucore_procs = { version="0.0.4", package="uucore_procs", git="https://github.com/uutils/uucore.git", branch="canary" }

[[bin]]
name = "mkfifo"
path = "src/main.rs"
