[package]
name = "mv"
version = "0.0.1"
authors = []
build = "../../mkmain.rs"

[lib]
name = "uu_mv"
path = "mv.rs"

[dependencies]
getopts = "0.2.18"
uucore = { path="../uucore" }

[[bin]]
name = "mv"
path = "../../uumain.rs"
