[package]
name = "mv"
version = "0.0.1"
authors = []

[lib]
name = "mv"
path = "mv.rs"

[dependencies]
getopts = "*"
libc = "*"
uucore = { path="../uucore" }

[dev-dependencies]
time = "*"

[[bin]]
name="mv"
path="mv.rs"
