[package]
name = "uu_hostname"
version = "0.0.1"
authors = []
license = "MIT"

[lib]
path = "src/hostname.rs"

[dependencies]
clap = "2.32"
libc = "0.2.42"
hostname = { version = "0.3", features = ["set"] }
uucore = { version="0.0.3", package="uucore", git="https://github.com/uutils/uucore.git", branch="canary", features=["wide"] }
uucore_procs = { version="0.0.3", package="uucore_procs", git="https://github.com/uutils/uucore.git", branch="canary" }
winapi = { version="0.3", features=["sysinfoapi", "winsock2"] }

[[bin]]
name = "hostname"
path = "src/main.rs"
