[package]
name = "uu_du"
version = "0.0.1"
authors = []
license = "MIT"

[lib]
path = "src/du.rs"

[dependencies]
time = "0.1.40"
uucore = { version="0.0.3", package="uucore", git="https://github.com/uutils/uucore.git", branch="canary" }
uucore_procs = { version="0.0.3", package="uucore_procs", git="https://github.com/uutils/uucore.git", branch="canary" }

[[bin]]
name = "du"
path = "src/main.rs"
