[package]
name = "uptime"
version = "0.0.1"
authors = []

[lib]
name = "uu_uptime"
path = "uptime.rs"

[dependencies]
getopts = "*"
libc = "*"
time = "*"
uucore = { path="../uucore" }

[[bin]]
name = "uptime"
path = "main.rs"
