[package]
name = "uu_cat"
version = "0.0.1"
authors = []
license = "MIT"

[lib]
path = "src/cat.rs"

[dependencies]
quick-error = "1.2.3"
uucore = { version="0.0.3", package="uucore", git="https://github.com/uutils/uucore.git", branch="canary", features=["fs"] }
uucore_procs = { version="0.0.3", package="uucore_procs", git="https://github.com/uutils/uucore.git", branch="canary" }

[target.'cfg(unix)'.dependencies]
unix_socket = "0.5.0"

[[bin]]
name = "cat"
path = "src/main.rs"
