[package]
name = "uu_chmod"
version = "0.0.1"
authors = ["uutils developers"]
license = "MIT"
description = "chmod ~ (uutils) change mode of FILES"

homepage = "https://github.com/uutils/coreutils"
repository = "https://github.com/uutils/coreutils/tree/master/src/uu/chmod"

[lib]
path = "src/chmod.rs"

[dependencies]
libc = "0.2.42"
uucore = { version="0.0.3", package="uucore", git="https://github.com/uutils/uucore.git", branch="canary", features=["mode"] }
uucore_procs = { version="0.0.3", package="uucore_procs", git="https://github.com/uutils/uucore.git", branch="canary" }
walker = "1.0.0"

[[bin]]
name = "chmod"
path = "src/main.rs"
