[package]
name = "uu_touch"
version = "0.0.1"
authors = []
license = "MIT"

[lib]
path = "src/touch.rs"

[dependencies]
filetime = "0.2.1"
getopts = "0.2.18"
time = "0.1.40"
uucore = { version="0.0.3", package="uucore", git="https://github.com/uutils/uucore.git", branch="canary", features=["libc"] }
uucore_procs = { version="0.0.3", package="uucore_procs", git="https://github.com/uutils/uucore.git", branch="canary" }

[[bin]]
name = "touch"
path = "src/main.rs"
