[package]
name = "uu_base32"
version = "0.0.1"
authors = ["uutils developers"]
license = "MIT"
description = "base32 ~ (uutils) decode/encode base32"

homepage = "https://github.com/uutils/coreutils"
repository = "https://github.com/uutils/coreutils/tree/master/src/uu/base32"

[lib]
path = "src/base32.rs"

[dependencies]
uucore = { version="0.0.3", package="uucore", git="https://github.com/uutils/uucore.git", branch="canary", features = ["encoding"] }
uucore_procs = { version="0.0.3", package="uucore_procs", git="https://github.com/uutils/uucore.git", branch="canary" }
## optional
clippy = { version = "0.0.212", optional = true }

[[bin]]
name = "base32"
path = "src/main.rs"
