[package]
name = "uu_nl"
version = "0.0.1"
authors = []
license = "MIT"

[lib]
path = "src/nl.rs"

[dependencies]
aho-corasick = "0.7.3"
getopts = "0.2.18"
libc = "0.2.42"
memchr = "2.2.0"
regex = "1.0.1"
regex-syntax = "0.6.7"
uucore = { version="0.0.3", package="uucore", git="https://github.com/uutils/uucore.git", branch="canary" }
uucore_procs = { version="0.0.3", package="uucore_procs", git="https://github.com/uutils/uucore.git", branch="canary" }

[[bin]]
name = "nl"
path = "src/main.rs"
