[package]
name = "rmdir"
version = "0.0.1"
authors = []

[lib]
name = "rmdir"
path = "rmdir.rs"

[dependencies]
getopts = "*"
libc = "*"
uucore = { path="../uucore" }

[[bin]]
name="rmdir"
path="rmdir.rs"
