[package]
name = "uu_chown"
version = "0.0.1"
authors = []
license = "MIT"

[lib]
path = "src/chown.rs"

[dependencies]
glob = "0.3.0"
uucore = { version="0.0.3", package="uucore", git="https://github.com/uutils/uucore.git", branch="canary", features=["entries", "fs"] }
uucore_procs = { version="0.0.3", package="uucore_procs", git="https://github.com/uutils/uucore.git", branch="canary" }
walkdir = "2.2"

[dependencies.clippy]
version = "0.0.212"
optional = true

[[bin]]
name = "chown"
path = "src/main.rs"
