[package]
name = "whoami"
version = "0.0.1"
authors = []

[lib]
name = "whoami"
path = "whoami.rs"

[dependencies]
getopts = "*"
libc = "*"
uucore = { path="../uucore" }

[[bin]]
name="whoami"
path="whoami.rs"
