[package]
name = "whoami"
version = "0.0.1"
authors = []
description = "Print effective user ID."
build = "../../mkmain.rs"

[lib]
name = "uu_whoami"
path = "whoami.rs"

[dependencies]
clap = "2.31"
winapi = { version = "0.3", features = ["lmcons"] }
advapi32-sys = "0.2.0"

[dependencies.uucore]
path = "../uucore"
features = ["entries", "wide"]

[[bin]]
name = "whoami"
path = "../../uumain.rs"
